# Generated by Django 5.2 on 2025-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento')], max_length=20)),
                ('titulo', models.CharField(max_length=225)),
                ('descripcion', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('fecha', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(max_length=10)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
